### ISSUE TITLE
vertice.cql not found

### ISSUE THREAD

**Issue by systemroot** [megamsys/vertice_gateway#441]
after i executed those
<pre>
* git clone https://github.com/<your_github_id>/vertice_gateway.git
* cd vertice_gateway
* sbt
* clean
* compile
</pre>
i can't find those, into vertice_gateway/conf dir.
<pre>
* cqlsh -f vertice.cql
* cqlsh -f upgrade_1.5.cql
* cqlsh -f marketplaces.cql
</pre>

and if i try "run" i'll get this error :confused: 

<pre>
[verticegateway] $ run
[trace] Stack trace suppressed: run last *:javaOptions for the full output.
[error] (*:javaOptions) Must define MEGAM_HOME
[error] Total time: 0 s, completed Nov 4, 2016 11:56:26 AM
[verticegateway] $ 
</pre>

Any Help? Thanks!

**Comment by ranjithamca** [comment]
@systemroot   
Thanks for showing the interest in the product.
we update readme file. Now you can test it.

**Comment by systemroot** [comment]
@ranjithamca thank you, now is working without problems!
a last question how to start UI (https://github.com/megamsys/nilavu) after installation !? Because hasn't start, i don't use ruby but well i was loking into config/folder trying to execute unicorn_launcher, but didn't work i'm getting a lot of errors (also i don't know what unicorn_launcher do! lol)

**Comment by indykish** [comment]
@systemroot  Can you join our forum [https://forum.megam.io](https://forum.megam.io)

so i can answer there.

I am closing this issue as the README.md is updated and this is  a different issue.

@ranjithamca fyi.
